# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import cdata_pb2 as cdata__pb2


class SQLClientStub(object):
    """a service for passing cooperative SQL statements to a rcd instance
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.IsOnline = channel.unary_unary(
                '/cdata.SQLClient/IsOnline',
                request_serializer=cdata__pb2.TestRequest.SerializeToString,
                response_deserializer=cdata__pb2.TestReply.FromString,
                )
        self.CreateUserDatabase = channel.unary_unary(
                '/cdata.SQLClient/CreateUserDatabase',
                request_serializer=cdata__pb2.CreateUserDatabaseRequest.SerializeToString,
                response_deserializer=cdata__pb2.CreateUserDatabaseReply.FromString,
                )
        self.EnableCoooperativeFeatures = channel.unary_unary(
                '/cdata.SQLClient/EnableCoooperativeFeatures',
                request_serializer=cdata__pb2.EnableCoooperativeFeaturesRequest.SerializeToString,
                response_deserializer=cdata__pb2.EnableCoooperativeFeaturesReply.FromString,
                )
        self.ExecuteRead = channel.unary_unary(
                '/cdata.SQLClient/ExecuteRead',
                request_serializer=cdata__pb2.ExecuteReadRequest.SerializeToString,
                response_deserializer=cdata__pb2.ExecuteReadReply.FromString,
                )
        self.ExecuteWrite = channel.unary_unary(
                '/cdata.SQLClient/ExecuteWrite',
                request_serializer=cdata__pb2.ExecuteWriteRequest.SerializeToString,
                response_deserializer=cdata__pb2.ExecuteWriteReply.FromString,
                )
        self.ExecuteCooperativeWrite = channel.unary_unary(
                '/cdata.SQLClient/ExecuteCooperativeWrite',
                request_serializer=cdata__pb2.ExecuteCooperativeWriteRequest.SerializeToString,
                response_deserializer=cdata__pb2.ExecuteCooperativeWriteReply.FromString,
                )
        self.HasTable = channel.unary_unary(
                '/cdata.SQLClient/HasTable',
                request_serializer=cdata__pb2.HasTableRequest.SerializeToString,
                response_deserializer=cdata__pb2.HasTableReply.FromString,
                )
        self.SetLogicalStoragePolicy = channel.unary_unary(
                '/cdata.SQLClient/SetLogicalStoragePolicy',
                request_serializer=cdata__pb2.SetLogicalStoragePolicyRequest.SerializeToString,
                response_deserializer=cdata__pb2.SetLogicalStoragePolicyReply.FromString,
                )
        self.GetLogicalStoragePolicy = channel.unary_unary(
                '/cdata.SQLClient/GetLogicalStoragePolicy',
                request_serializer=cdata__pb2.GetLogicalStoragePolicyRequest.SerializeToString,
                response_deserializer=cdata__pb2.GetLogicalStoragePolicyReply.FromString,
                )
        self.GenerateContract = channel.unary_unary(
                '/cdata.SQLClient/GenerateContract',
                request_serializer=cdata__pb2.GenerateContractRequest.SerializeToString,
                response_deserializer=cdata__pb2.GenerateContractReply.FromString,
                )
        self.AddParticipant = channel.unary_unary(
                '/cdata.SQLClient/AddParticipant',
                request_serializer=cdata__pb2.AddParticipantRequest.SerializeToString,
                response_deserializer=cdata__pb2.AddParticipantReply.FromString,
                )
        self.SendParticipantContract = channel.unary_unary(
                '/cdata.SQLClient/SendParticipantContract',
                request_serializer=cdata__pb2.SendParticipantContractRequest.SerializeToString,
                response_deserializer=cdata__pb2.SendParticipantContractReply.FromString,
                )
        self.ReviewPendingContracts = channel.unary_unary(
                '/cdata.SQLClient/ReviewPendingContracts',
                request_serializer=cdata__pb2.ViewPendingContractsRequest.SerializeToString,
                response_deserializer=cdata__pb2.ViewPendingContractsReply.FromString,
                )
        self.AcceptPendingContract = channel.unary_unary(
                '/cdata.SQLClient/AcceptPendingContract',
                request_serializer=cdata__pb2.AcceptPendingContractRequest.SerializeToString,
                response_deserializer=cdata__pb2.AcceptPendingContractReply.FromString,
                )
        self.RejectPendingContract = channel.unary_unary(
                '/cdata.SQLClient/RejectPendingContract',
                request_serializer=cdata__pb2.RejectPendingContractRequest.SerializeToString,
                response_deserializer=cdata__pb2.RejectPendingContractReply.FromString,
                )
        self.GenerateHostInfo = channel.unary_unary(
                '/cdata.SQLClient/GenerateHostInfo',
                request_serializer=cdata__pb2.GenerateHostInfoRequest.SerializeToString,
                response_deserializer=cdata__pb2.GenerateHostInfoReply.FromString,
                )
        self.ChangeHostStatus = channel.unary_unary(
                '/cdata.SQLClient/ChangeHostStatus',
                request_serializer=cdata__pb2.ChangeHostStatusRequest.SerializeToString,
                response_deserializer=cdata__pb2.ChangeHostStatusReply.FromString,
                )
        self.TryAuthAtParticipant = channel.unary_unary(
                '/cdata.SQLClient/TryAuthAtParticipant',
                request_serializer=cdata__pb2.TryAuthAtParticipantRequest.SerializeToString,
                response_deserializer=cdata__pb2.TryAuthAtPartipantReply.FromString,
                )


class SQLClientServicer(object):
    """a service for passing cooperative SQL statements to a rcd instance
    """

    def IsOnline(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateUserDatabase(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EnableCoooperativeFeatures(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ExecuteRead(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ExecuteWrite(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ExecuteCooperativeWrite(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HasTable(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetLogicalStoragePolicy(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetLogicalStoragePolicy(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GenerateContract(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AddParticipant(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendParticipantContract(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReviewPendingContracts(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AcceptPendingContract(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RejectPendingContract(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GenerateHostInfo(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ChangeHostStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def TryAuthAtParticipant(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SQLClientServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'IsOnline': grpc.unary_unary_rpc_method_handler(
                    servicer.IsOnline,
                    request_deserializer=cdata__pb2.TestRequest.FromString,
                    response_serializer=cdata__pb2.TestReply.SerializeToString,
            ),
            'CreateUserDatabase': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateUserDatabase,
                    request_deserializer=cdata__pb2.CreateUserDatabaseRequest.FromString,
                    response_serializer=cdata__pb2.CreateUserDatabaseReply.SerializeToString,
            ),
            'EnableCoooperativeFeatures': grpc.unary_unary_rpc_method_handler(
                    servicer.EnableCoooperativeFeatures,
                    request_deserializer=cdata__pb2.EnableCoooperativeFeaturesRequest.FromString,
                    response_serializer=cdata__pb2.EnableCoooperativeFeaturesReply.SerializeToString,
            ),
            'ExecuteRead': grpc.unary_unary_rpc_method_handler(
                    servicer.ExecuteRead,
                    request_deserializer=cdata__pb2.ExecuteReadRequest.FromString,
                    response_serializer=cdata__pb2.ExecuteReadReply.SerializeToString,
            ),
            'ExecuteWrite': grpc.unary_unary_rpc_method_handler(
                    servicer.ExecuteWrite,
                    request_deserializer=cdata__pb2.ExecuteWriteRequest.FromString,
                    response_serializer=cdata__pb2.ExecuteWriteReply.SerializeToString,
            ),
            'ExecuteCooperativeWrite': grpc.unary_unary_rpc_method_handler(
                    servicer.ExecuteCooperativeWrite,
                    request_deserializer=cdata__pb2.ExecuteCooperativeWriteRequest.FromString,
                    response_serializer=cdata__pb2.ExecuteCooperativeWriteReply.SerializeToString,
            ),
            'HasTable': grpc.unary_unary_rpc_method_handler(
                    servicer.HasTable,
                    request_deserializer=cdata__pb2.HasTableRequest.FromString,
                    response_serializer=cdata__pb2.HasTableReply.SerializeToString,
            ),
            'SetLogicalStoragePolicy': grpc.unary_unary_rpc_method_handler(
                    servicer.SetLogicalStoragePolicy,
                    request_deserializer=cdata__pb2.SetLogicalStoragePolicyRequest.FromString,
                    response_serializer=cdata__pb2.SetLogicalStoragePolicyReply.SerializeToString,
            ),
            'GetLogicalStoragePolicy': grpc.unary_unary_rpc_method_handler(
                    servicer.GetLogicalStoragePolicy,
                    request_deserializer=cdata__pb2.GetLogicalStoragePolicyRequest.FromString,
                    response_serializer=cdata__pb2.GetLogicalStoragePolicyReply.SerializeToString,
            ),
            'GenerateContract': grpc.unary_unary_rpc_method_handler(
                    servicer.GenerateContract,
                    request_deserializer=cdata__pb2.GenerateContractRequest.FromString,
                    response_serializer=cdata__pb2.GenerateContractReply.SerializeToString,
            ),
            'AddParticipant': grpc.unary_unary_rpc_method_handler(
                    servicer.AddParticipant,
                    request_deserializer=cdata__pb2.AddParticipantRequest.FromString,
                    response_serializer=cdata__pb2.AddParticipantReply.SerializeToString,
            ),
            'SendParticipantContract': grpc.unary_unary_rpc_method_handler(
                    servicer.SendParticipantContract,
                    request_deserializer=cdata__pb2.SendParticipantContractRequest.FromString,
                    response_serializer=cdata__pb2.SendParticipantContractReply.SerializeToString,
            ),
            'ReviewPendingContracts': grpc.unary_unary_rpc_method_handler(
                    servicer.ReviewPendingContracts,
                    request_deserializer=cdata__pb2.ViewPendingContractsRequest.FromString,
                    response_serializer=cdata__pb2.ViewPendingContractsReply.SerializeToString,
            ),
            'AcceptPendingContract': grpc.unary_unary_rpc_method_handler(
                    servicer.AcceptPendingContract,
                    request_deserializer=cdata__pb2.AcceptPendingContractRequest.FromString,
                    response_serializer=cdata__pb2.AcceptPendingContractReply.SerializeToString,
            ),
            'RejectPendingContract': grpc.unary_unary_rpc_method_handler(
                    servicer.RejectPendingContract,
                    request_deserializer=cdata__pb2.RejectPendingContractRequest.FromString,
                    response_serializer=cdata__pb2.RejectPendingContractReply.SerializeToString,
            ),
            'GenerateHostInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.GenerateHostInfo,
                    request_deserializer=cdata__pb2.GenerateHostInfoRequest.FromString,
                    response_serializer=cdata__pb2.GenerateHostInfoReply.SerializeToString,
            ),
            'ChangeHostStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.ChangeHostStatus,
                    request_deserializer=cdata__pb2.ChangeHostStatusRequest.FromString,
                    response_serializer=cdata__pb2.ChangeHostStatusReply.SerializeToString,
            ),
            'TryAuthAtParticipant': grpc.unary_unary_rpc_method_handler(
                    servicer.TryAuthAtParticipant,
                    request_deserializer=cdata__pb2.TryAuthAtParticipantRequest.FromString,
                    response_serializer=cdata__pb2.TryAuthAtPartipantReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'cdata.SQLClient', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class SQLClient(object):
    """a service for passing cooperative SQL statements to a rcd instance
    """

    @staticmethod
    def IsOnline(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/cdata.SQLClient/IsOnline',
            cdata__pb2.TestRequest.SerializeToString,
            cdata__pb2.TestReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CreateUserDatabase(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/cdata.SQLClient/CreateUserDatabase',
            cdata__pb2.CreateUserDatabaseRequest.SerializeToString,
            cdata__pb2.CreateUserDatabaseReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def EnableCoooperativeFeatures(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/cdata.SQLClient/EnableCoooperativeFeatures',
            cdata__pb2.EnableCoooperativeFeaturesRequest.SerializeToString,
            cdata__pb2.EnableCoooperativeFeaturesReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ExecuteRead(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/cdata.SQLClient/ExecuteRead',
            cdata__pb2.ExecuteReadRequest.SerializeToString,
            cdata__pb2.ExecuteReadReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ExecuteWrite(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/cdata.SQLClient/ExecuteWrite',
            cdata__pb2.ExecuteWriteRequest.SerializeToString,
            cdata__pb2.ExecuteWriteReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ExecuteCooperativeWrite(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/cdata.SQLClient/ExecuteCooperativeWrite',
            cdata__pb2.ExecuteCooperativeWriteRequest.SerializeToString,
            cdata__pb2.ExecuteCooperativeWriteReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def HasTable(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/cdata.SQLClient/HasTable',
            cdata__pb2.HasTableRequest.SerializeToString,
            cdata__pb2.HasTableReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SetLogicalStoragePolicy(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/cdata.SQLClient/SetLogicalStoragePolicy',
            cdata__pb2.SetLogicalStoragePolicyRequest.SerializeToString,
            cdata__pb2.SetLogicalStoragePolicyReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetLogicalStoragePolicy(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/cdata.SQLClient/GetLogicalStoragePolicy',
            cdata__pb2.GetLogicalStoragePolicyRequest.SerializeToString,
            cdata__pb2.GetLogicalStoragePolicyReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GenerateContract(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/cdata.SQLClient/GenerateContract',
            cdata__pb2.GenerateContractRequest.SerializeToString,
            cdata__pb2.GenerateContractReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def AddParticipant(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/cdata.SQLClient/AddParticipant',
            cdata__pb2.AddParticipantRequest.SerializeToString,
            cdata__pb2.AddParticipantReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SendParticipantContract(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/cdata.SQLClient/SendParticipantContract',
            cdata__pb2.SendParticipantContractRequest.SerializeToString,
            cdata__pb2.SendParticipantContractReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ReviewPendingContracts(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/cdata.SQLClient/ReviewPendingContracts',
            cdata__pb2.ViewPendingContractsRequest.SerializeToString,
            cdata__pb2.ViewPendingContractsReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def AcceptPendingContract(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/cdata.SQLClient/AcceptPendingContract',
            cdata__pb2.AcceptPendingContractRequest.SerializeToString,
            cdata__pb2.AcceptPendingContractReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def RejectPendingContract(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/cdata.SQLClient/RejectPendingContract',
            cdata__pb2.RejectPendingContractRequest.SerializeToString,
            cdata__pb2.RejectPendingContractReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GenerateHostInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/cdata.SQLClient/GenerateHostInfo',
            cdata__pb2.GenerateHostInfoRequest.SerializeToString,
            cdata__pb2.GenerateHostInfoReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ChangeHostStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/cdata.SQLClient/ChangeHostStatus',
            cdata__pb2.ChangeHostStatusRequest.SerializeToString,
            cdata__pb2.ChangeHostStatusReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def TryAuthAtParticipant(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/cdata.SQLClient/TryAuthAtParticipant',
            cdata__pb2.TryAuthAtParticipantRequest.SerializeToString,
            cdata__pb2.TryAuthAtPartipantReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)


class DataServiceStub(object):
    """a service for communication between different rcd stores
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.IsOnline = channel.unary_unary(
                '/cdata.DataService/IsOnline',
                request_serializer=cdata__pb2.TestRequest.SerializeToString,
                response_deserializer=cdata__pb2.TestReply.FromString,
                )
        self.CreatePartialDatabase = channel.unary_unary(
                '/cdata.DataService/CreatePartialDatabase',
                request_serializer=cdata__pb2.CreateDatabaseRequest.SerializeToString,
                response_deserializer=cdata__pb2.CreateDatabaseResult.FromString,
                )
        self.CreateTableInDatabase = channel.unary_unary(
                '/cdata.DataService/CreateTableInDatabase',
                request_serializer=cdata__pb2.CreateTableRequest.SerializeToString,
                response_deserializer=cdata__pb2.CreateTableResult.FromString,
                )
        self.InsertCommandIntoTable = channel.unary_unary(
                '/cdata.DataService/InsertCommandIntoTable',
                request_serializer=cdata__pb2.InsertDataRequest.SerializeToString,
                response_deserializer=cdata__pb2.InsertDataResult.FromString,
                )
        self.UpdateCommandIntoTable = channel.unary_unary(
                '/cdata.DataService/UpdateCommandIntoTable',
                request_serializer=cdata__pb2.UpdateDataRequest.SerializeToString,
                response_deserializer=cdata__pb2.UpdateDataResult.FromString,
                )
        self.DeleteCommandIntoTable = channel.unary_unary(
                '/cdata.DataService/DeleteCommandIntoTable',
                request_serializer=cdata__pb2.DeleteDataRequest.SerializeToString,
                response_deserializer=cdata__pb2.DeleteDataResult.FromString,
                )
        self.GetRowFromPartialDatabase = channel.unary_unary(
                '/cdata.DataService/GetRowFromPartialDatabase',
                request_serializer=cdata__pb2.GetRowFromPartialDatabaseRequest.SerializeToString,
                response_deserializer=cdata__pb2.GetRowFromPartialDatabaseResult.FromString,
                )
        self.SaveContract = channel.unary_unary(
                '/cdata.DataService/SaveContract',
                request_serializer=cdata__pb2.SaveContractRequest.SerializeToString,
                response_deserializer=cdata__pb2.SaveContractResult.FromString,
                )
        self.AcceptContract = channel.unary_unary(
                '/cdata.DataService/AcceptContract',
                request_serializer=cdata__pb2.ParticipantAcceptsContractRequest.SerializeToString,
                response_deserializer=cdata__pb2.ParticipantAcceptsContractResult.FromString,
                )
        self.UpdateRowDataHashForHost = channel.unary_unary(
                '/cdata.DataService/UpdateRowDataHashForHost',
                request_serializer=cdata__pb2.UpdateRowDataHashForHostRequest.SerializeToString,
                response_deserializer=cdata__pb2.UpdateRowDataHashForHostResponse.FromString,
                )
        self.NotifyHostOfRemovedRow = channel.unary_unary(
                '/cdata.DataService/NotifyHostOfRemovedRow',
                request_serializer=cdata__pb2.NotifyHostOfRemovedRowRequest.SerializeToString,
                response_deserializer=cdata__pb2.NotifyHostOfRemovedRowResponse.FromString,
                )
        self.TryAuth = channel.unary_unary(
                '/cdata.DataService/TryAuth',
                request_serializer=cdata__pb2.TryAuthRequest.SerializeToString,
                response_deserializer=cdata__pb2.TryAuthResult.FromString,
                )


class DataServiceServicer(object):
    """a service for communication between different rcd stores
    """

    def IsOnline(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreatePartialDatabase(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateTableInDatabase(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def InsertCommandIntoTable(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateCommandIntoTable(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteCommandIntoTable(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetRowFromPartialDatabase(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SaveContract(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AcceptContract(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateRowDataHashForHost(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def NotifyHostOfRemovedRow(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def TryAuth(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DataServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'IsOnline': grpc.unary_unary_rpc_method_handler(
                    servicer.IsOnline,
                    request_deserializer=cdata__pb2.TestRequest.FromString,
                    response_serializer=cdata__pb2.TestReply.SerializeToString,
            ),
            'CreatePartialDatabase': grpc.unary_unary_rpc_method_handler(
                    servicer.CreatePartialDatabase,
                    request_deserializer=cdata__pb2.CreateDatabaseRequest.FromString,
                    response_serializer=cdata__pb2.CreateDatabaseResult.SerializeToString,
            ),
            'CreateTableInDatabase': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateTableInDatabase,
                    request_deserializer=cdata__pb2.CreateTableRequest.FromString,
                    response_serializer=cdata__pb2.CreateTableResult.SerializeToString,
            ),
            'InsertCommandIntoTable': grpc.unary_unary_rpc_method_handler(
                    servicer.InsertCommandIntoTable,
                    request_deserializer=cdata__pb2.InsertDataRequest.FromString,
                    response_serializer=cdata__pb2.InsertDataResult.SerializeToString,
            ),
            'UpdateCommandIntoTable': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateCommandIntoTable,
                    request_deserializer=cdata__pb2.UpdateDataRequest.FromString,
                    response_serializer=cdata__pb2.UpdateDataResult.SerializeToString,
            ),
            'DeleteCommandIntoTable': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteCommandIntoTable,
                    request_deserializer=cdata__pb2.DeleteDataRequest.FromString,
                    response_serializer=cdata__pb2.DeleteDataResult.SerializeToString,
            ),
            'GetRowFromPartialDatabase': grpc.unary_unary_rpc_method_handler(
                    servicer.GetRowFromPartialDatabase,
                    request_deserializer=cdata__pb2.GetRowFromPartialDatabaseRequest.FromString,
                    response_serializer=cdata__pb2.GetRowFromPartialDatabaseResult.SerializeToString,
            ),
            'SaveContract': grpc.unary_unary_rpc_method_handler(
                    servicer.SaveContract,
                    request_deserializer=cdata__pb2.SaveContractRequest.FromString,
                    response_serializer=cdata__pb2.SaveContractResult.SerializeToString,
            ),
            'AcceptContract': grpc.unary_unary_rpc_method_handler(
                    servicer.AcceptContract,
                    request_deserializer=cdata__pb2.ParticipantAcceptsContractRequest.FromString,
                    response_serializer=cdata__pb2.ParticipantAcceptsContractResult.SerializeToString,
            ),
            'UpdateRowDataHashForHost': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateRowDataHashForHost,
                    request_deserializer=cdata__pb2.UpdateRowDataHashForHostRequest.FromString,
                    response_serializer=cdata__pb2.UpdateRowDataHashForHostResponse.SerializeToString,
            ),
            'NotifyHostOfRemovedRow': grpc.unary_unary_rpc_method_handler(
                    servicer.NotifyHostOfRemovedRow,
                    request_deserializer=cdata__pb2.NotifyHostOfRemovedRowRequest.FromString,
                    response_serializer=cdata__pb2.NotifyHostOfRemovedRowResponse.SerializeToString,
            ),
            'TryAuth': grpc.unary_unary_rpc_method_handler(
                    servicer.TryAuth,
                    request_deserializer=cdata__pb2.TryAuthRequest.FromString,
                    response_serializer=cdata__pb2.TryAuthResult.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'cdata.DataService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class DataService(object):
    """a service for communication between different rcd stores
    """

    @staticmethod
    def IsOnline(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/cdata.DataService/IsOnline',
            cdata__pb2.TestRequest.SerializeToString,
            cdata__pb2.TestReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CreatePartialDatabase(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/cdata.DataService/CreatePartialDatabase',
            cdata__pb2.CreateDatabaseRequest.SerializeToString,
            cdata__pb2.CreateDatabaseResult.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CreateTableInDatabase(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/cdata.DataService/CreateTableInDatabase',
            cdata__pb2.CreateTableRequest.SerializeToString,
            cdata__pb2.CreateTableResult.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def InsertCommandIntoTable(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/cdata.DataService/InsertCommandIntoTable',
            cdata__pb2.InsertDataRequest.SerializeToString,
            cdata__pb2.InsertDataResult.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def UpdateCommandIntoTable(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/cdata.DataService/UpdateCommandIntoTable',
            cdata__pb2.UpdateDataRequest.SerializeToString,
            cdata__pb2.UpdateDataResult.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DeleteCommandIntoTable(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/cdata.DataService/DeleteCommandIntoTable',
            cdata__pb2.DeleteDataRequest.SerializeToString,
            cdata__pb2.DeleteDataResult.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetRowFromPartialDatabase(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/cdata.DataService/GetRowFromPartialDatabase',
            cdata__pb2.GetRowFromPartialDatabaseRequest.SerializeToString,
            cdata__pb2.GetRowFromPartialDatabaseResult.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SaveContract(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/cdata.DataService/SaveContract',
            cdata__pb2.SaveContractRequest.SerializeToString,
            cdata__pb2.SaveContractResult.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def AcceptContract(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/cdata.DataService/AcceptContract',
            cdata__pb2.ParticipantAcceptsContractRequest.SerializeToString,
            cdata__pb2.ParticipantAcceptsContractResult.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def UpdateRowDataHashForHost(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/cdata.DataService/UpdateRowDataHashForHost',
            cdata__pb2.UpdateRowDataHashForHostRequest.SerializeToString,
            cdata__pb2.UpdateRowDataHashForHostResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def NotifyHostOfRemovedRow(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/cdata.DataService/NotifyHostOfRemovedRow',
            cdata__pb2.NotifyHostOfRemovedRowRequest.SerializeToString,
            cdata__pb2.NotifyHostOfRemovedRowResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def TryAuth(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/cdata.DataService/TryAuth',
            cdata__pb2.TryAuthRequest.SerializeToString,
            cdata__pb2.TryAuthResult.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
