# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import rcdp_pb2 as rcdp__pb2


class SQLClientStub(object):
    """a service for passing cooperative SQL statements to a rcd instance
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.IsOnline = channel.unary_unary(
                '/rcdp.SQLClient/IsOnline',
                request_serializer=rcdp__pb2.TestRequest.SerializeToString,
                response_deserializer=rcdp__pb2.TestReply.FromString,
                )
        self.CreateUserDatabase = channel.unary_unary(
                '/rcdp.SQLClient/CreateUserDatabase',
                request_serializer=rcdp__pb2.CreateUserDatabaseRequest.SerializeToString,
                response_deserializer=rcdp__pb2.CreateUserDatabaseReply.FromString,
                )
        self.EnableCoooperativeFeatures = channel.unary_unary(
                '/rcdp.SQLClient/EnableCoooperativeFeatures',
                request_serializer=rcdp__pb2.EnableCoooperativeFeaturesRequest.SerializeToString,
                response_deserializer=rcdp__pb2.EnableCoooperativeFeaturesReply.FromString,
                )
        self.ExecuteReadAtHost = channel.unary_unary(
                '/rcdp.SQLClient/ExecuteReadAtHost',
                request_serializer=rcdp__pb2.ExecuteReadRequest.SerializeToString,
                response_deserializer=rcdp__pb2.ExecuteReadReply.FromString,
                )
        self.ExecuteWriteAtHost = channel.unary_unary(
                '/rcdp.SQLClient/ExecuteWriteAtHost',
                request_serializer=rcdp__pb2.ExecuteWriteRequest.SerializeToString,
                response_deserializer=rcdp__pb2.ExecuteWriteReply.FromString,
                )
        self.ExecuteCooperativeWriteAtHost = channel.unary_unary(
                '/rcdp.SQLClient/ExecuteCooperativeWriteAtHost',
                request_serializer=rcdp__pb2.ExecuteCooperativeWriteRequest.SerializeToString,
                response_deserializer=rcdp__pb2.ExecuteCooperativeWriteReply.FromString,
                )
        self.ExecuteReadAtParticipant = channel.unary_unary(
                '/rcdp.SQLClient/ExecuteReadAtParticipant',
                request_serializer=rcdp__pb2.ExecuteReadRequest.SerializeToString,
                response_deserializer=rcdp__pb2.ExecuteReadReply.FromString,
                )
        self.ExecuteWriteAtParticipant = channel.unary_unary(
                '/rcdp.SQLClient/ExecuteWriteAtParticipant',
                request_serializer=rcdp__pb2.ExecuteWriteRequest.SerializeToString,
                response_deserializer=rcdp__pb2.ExecuteWriteReply.FromString,
                )
        self.HasTable = channel.unary_unary(
                '/rcdp.SQLClient/HasTable',
                request_serializer=rcdp__pb2.HasTableRequest.SerializeToString,
                response_deserializer=rcdp__pb2.HasTableReply.FromString,
                )
        self.SetLogicalStoragePolicy = channel.unary_unary(
                '/rcdp.SQLClient/SetLogicalStoragePolicy',
                request_serializer=rcdp__pb2.SetLogicalStoragePolicyRequest.SerializeToString,
                response_deserializer=rcdp__pb2.SetLogicalStoragePolicyReply.FromString,
                )
        self.GetLogicalStoragePolicy = channel.unary_unary(
                '/rcdp.SQLClient/GetLogicalStoragePolicy',
                request_serializer=rcdp__pb2.GetLogicalStoragePolicyRequest.SerializeToString,
                response_deserializer=rcdp__pb2.GetLogicalStoragePolicyReply.FromString,
                )
        self.GenerateContract = channel.unary_unary(
                '/rcdp.SQLClient/GenerateContract',
                request_serializer=rcdp__pb2.GenerateContractRequest.SerializeToString,
                response_deserializer=rcdp__pb2.GenerateContractReply.FromString,
                )
        self.AddParticipant = channel.unary_unary(
                '/rcdp.SQLClient/AddParticipant',
                request_serializer=rcdp__pb2.AddParticipantRequest.SerializeToString,
                response_deserializer=rcdp__pb2.AddParticipantReply.FromString,
                )
        self.SendParticipantContract = channel.unary_unary(
                '/rcdp.SQLClient/SendParticipantContract',
                request_serializer=rcdp__pb2.SendParticipantContractRequest.SerializeToString,
                response_deserializer=rcdp__pb2.SendParticipantContractReply.FromString,
                )
        self.ReviewPendingContracts = channel.unary_unary(
                '/rcdp.SQLClient/ReviewPendingContracts',
                request_serializer=rcdp__pb2.ViewPendingContractsRequest.SerializeToString,
                response_deserializer=rcdp__pb2.ViewPendingContractsReply.FromString,
                )
        self.AcceptPendingContract = channel.unary_unary(
                '/rcdp.SQLClient/AcceptPendingContract',
                request_serializer=rcdp__pb2.AcceptPendingContractRequest.SerializeToString,
                response_deserializer=rcdp__pb2.AcceptPendingContractReply.FromString,
                )
        self.RejectPendingContract = channel.unary_unary(
                '/rcdp.SQLClient/RejectPendingContract',
                request_serializer=rcdp__pb2.RejectPendingContractRequest.SerializeToString,
                response_deserializer=rcdp__pb2.RejectPendingContractReply.FromString,
                )
        self.GenerateHostInfo = channel.unary_unary(
                '/rcdp.SQLClient/GenerateHostInfo',
                request_serializer=rcdp__pb2.GenerateHostInfoRequest.SerializeToString,
                response_deserializer=rcdp__pb2.GenerateHostInfoReply.FromString,
                )
        self.ChangeHostStatus = channel.unary_unary(
                '/rcdp.SQLClient/ChangeHostStatus',
                request_serializer=rcdp__pb2.ChangeHostStatusRequest.SerializeToString,
                response_deserializer=rcdp__pb2.ChangeHostStatusReply.FromString,
                )
        self.TryAuthAtParticipant = channel.unary_unary(
                '/rcdp.SQLClient/TryAuthAtParticipant',
                request_serializer=rcdp__pb2.TryAuthAtParticipantRequest.SerializeToString,
                response_deserializer=rcdp__pb2.TryAuthAtPartipantReply.FromString,
                )
        self.ChangeUpdatesFromHostBehavior = channel.unary_unary(
                '/rcdp.SQLClient/ChangeUpdatesFromHostBehavior',
                request_serializer=rcdp__pb2.ChangeUpdatesFromHostBehaviorRequest.SerializeToString,
                response_deserializer=rcdp__pb2.ChangesUpdatesFromHostBehaviorReply.FromString,
                )
        self.ChangeDeletesFromHostBehavior = channel.unary_unary(
                '/rcdp.SQLClient/ChangeDeletesFromHostBehavior',
                request_serializer=rcdp__pb2.ChangeDeletesFromHostBehaviorRequest.SerializeToString,
                response_deserializer=rcdp__pb2.ChangeDeletesFromHostBehaviorReply.FromString,
                )
        self.ChangeUpdatesToHostBehavior = channel.unary_unary(
                '/rcdp.SQLClient/ChangeUpdatesToHostBehavior',
                request_serializer=rcdp__pb2.ChangeUpdatesToHostBehaviorRequest.SerializeToString,
                response_deserializer=rcdp__pb2.ChangeUpdatesToHostBehaviorReply.FromString,
                )
        self.ChangeDeletesToHostBehavior = channel.unary_unary(
                '/rcdp.SQLClient/ChangeDeletesToHostBehavior',
                request_serializer=rcdp__pb2.ChangeDeletesToHostBehaviorRequest.SerializeToString,
                response_deserializer=rcdp__pb2.ChangeDeletesToHostBehaviorReply.FromString,
                )
        self.GetDataHashAtHost = channel.unary_unary(
                '/rcdp.SQLClient/GetDataHashAtHost',
                request_serializer=rcdp__pb2.GetDataHashRequest.SerializeToString,
                response_deserializer=rcdp__pb2.GetDataHashReply.FromString,
                )
        self.GetDataHashAtParticipant = channel.unary_unary(
                '/rcdp.SQLClient/GetDataHashAtParticipant',
                request_serializer=rcdp__pb2.GetDataHashRequest.SerializeToString,
                response_deserializer=rcdp__pb2.GetDataHashReply.FromString,
                )
        self.ReadRowIdAtParticipant = channel.unary_unary(
                '/rcdp.SQLClient/ReadRowIdAtParticipant',
                request_serializer=rcdp__pb2.GetReadRowIdsRequest.SerializeToString,
                response_deserializer=rcdp__pb2.GetReadRowIdsReply.FromString,
                )
        self.GetDataLogTableStatusAtParticipant = channel.unary_unary(
                '/rcdp.SQLClient/GetDataLogTableStatusAtParticipant',
                request_serializer=rcdp__pb2.GetDataLogTableStatusRequest.SerializeToString,
                response_deserializer=rcdp__pb2.GetDataLogTableStatusReply.FromString,
                )
        self.SetDataLogTableStatusAtParticipant = channel.unary_unary(
                '/rcdp.SQLClient/SetDataLogTableStatusAtParticipant',
                request_serializer=rcdp__pb2.SetDataLogTableStatusRequest.SerializeToString,
                response_deserializer=rcdp__pb2.SetDataLogTableStatusReply.FromString,
                )


class SQLClientServicer(object):
    """a service for passing cooperative SQL statements to a rcd instance
    """

    def IsOnline(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateUserDatabase(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EnableCoooperativeFeatures(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ExecuteReadAtHost(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ExecuteWriteAtHost(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ExecuteCooperativeWriteAtHost(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ExecuteReadAtParticipant(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ExecuteWriteAtParticipant(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HasTable(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetLogicalStoragePolicy(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetLogicalStoragePolicy(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GenerateContract(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AddParticipant(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendParticipantContract(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReviewPendingContracts(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AcceptPendingContract(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RejectPendingContract(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GenerateHostInfo(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ChangeHostStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def TryAuthAtParticipant(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ChangeUpdatesFromHostBehavior(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ChangeDeletesFromHostBehavior(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ChangeUpdatesToHostBehavior(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ChangeDeletesToHostBehavior(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetDataHashAtHost(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetDataHashAtParticipant(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReadRowIdAtParticipant(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetDataLogTableStatusAtParticipant(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetDataLogTableStatusAtParticipant(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SQLClientServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'IsOnline': grpc.unary_unary_rpc_method_handler(
                    servicer.IsOnline,
                    request_deserializer=rcdp__pb2.TestRequest.FromString,
                    response_serializer=rcdp__pb2.TestReply.SerializeToString,
            ),
            'CreateUserDatabase': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateUserDatabase,
                    request_deserializer=rcdp__pb2.CreateUserDatabaseRequest.FromString,
                    response_serializer=rcdp__pb2.CreateUserDatabaseReply.SerializeToString,
            ),
            'EnableCoooperativeFeatures': grpc.unary_unary_rpc_method_handler(
                    servicer.EnableCoooperativeFeatures,
                    request_deserializer=rcdp__pb2.EnableCoooperativeFeaturesRequest.FromString,
                    response_serializer=rcdp__pb2.EnableCoooperativeFeaturesReply.SerializeToString,
            ),
            'ExecuteReadAtHost': grpc.unary_unary_rpc_method_handler(
                    servicer.ExecuteReadAtHost,
                    request_deserializer=rcdp__pb2.ExecuteReadRequest.FromString,
                    response_serializer=rcdp__pb2.ExecuteReadReply.SerializeToString,
            ),
            'ExecuteWriteAtHost': grpc.unary_unary_rpc_method_handler(
                    servicer.ExecuteWriteAtHost,
                    request_deserializer=rcdp__pb2.ExecuteWriteRequest.FromString,
                    response_serializer=rcdp__pb2.ExecuteWriteReply.SerializeToString,
            ),
            'ExecuteCooperativeWriteAtHost': grpc.unary_unary_rpc_method_handler(
                    servicer.ExecuteCooperativeWriteAtHost,
                    request_deserializer=rcdp__pb2.ExecuteCooperativeWriteRequest.FromString,
                    response_serializer=rcdp__pb2.ExecuteCooperativeWriteReply.SerializeToString,
            ),
            'ExecuteReadAtParticipant': grpc.unary_unary_rpc_method_handler(
                    servicer.ExecuteReadAtParticipant,
                    request_deserializer=rcdp__pb2.ExecuteReadRequest.FromString,
                    response_serializer=rcdp__pb2.ExecuteReadReply.SerializeToString,
            ),
            'ExecuteWriteAtParticipant': grpc.unary_unary_rpc_method_handler(
                    servicer.ExecuteWriteAtParticipant,
                    request_deserializer=rcdp__pb2.ExecuteWriteRequest.FromString,
                    response_serializer=rcdp__pb2.ExecuteWriteReply.SerializeToString,
            ),
            'HasTable': grpc.unary_unary_rpc_method_handler(
                    servicer.HasTable,
                    request_deserializer=rcdp__pb2.HasTableRequest.FromString,
                    response_serializer=rcdp__pb2.HasTableReply.SerializeToString,
            ),
            'SetLogicalStoragePolicy': grpc.unary_unary_rpc_method_handler(
                    servicer.SetLogicalStoragePolicy,
                    request_deserializer=rcdp__pb2.SetLogicalStoragePolicyRequest.FromString,
                    response_serializer=rcdp__pb2.SetLogicalStoragePolicyReply.SerializeToString,
            ),
            'GetLogicalStoragePolicy': grpc.unary_unary_rpc_method_handler(
                    servicer.GetLogicalStoragePolicy,
                    request_deserializer=rcdp__pb2.GetLogicalStoragePolicyRequest.FromString,
                    response_serializer=rcdp__pb2.GetLogicalStoragePolicyReply.SerializeToString,
            ),
            'GenerateContract': grpc.unary_unary_rpc_method_handler(
                    servicer.GenerateContract,
                    request_deserializer=rcdp__pb2.GenerateContractRequest.FromString,
                    response_serializer=rcdp__pb2.GenerateContractReply.SerializeToString,
            ),
            'AddParticipant': grpc.unary_unary_rpc_method_handler(
                    servicer.AddParticipant,
                    request_deserializer=rcdp__pb2.AddParticipantRequest.FromString,
                    response_serializer=rcdp__pb2.AddParticipantReply.SerializeToString,
            ),
            'SendParticipantContract': grpc.unary_unary_rpc_method_handler(
                    servicer.SendParticipantContract,
                    request_deserializer=rcdp__pb2.SendParticipantContractRequest.FromString,
                    response_serializer=rcdp__pb2.SendParticipantContractReply.SerializeToString,
            ),
            'ReviewPendingContracts': grpc.unary_unary_rpc_method_handler(
                    servicer.ReviewPendingContracts,
                    request_deserializer=rcdp__pb2.ViewPendingContractsRequest.FromString,
                    response_serializer=rcdp__pb2.ViewPendingContractsReply.SerializeToString,
            ),
            'AcceptPendingContract': grpc.unary_unary_rpc_method_handler(
                    servicer.AcceptPendingContract,
                    request_deserializer=rcdp__pb2.AcceptPendingContractRequest.FromString,
                    response_serializer=rcdp__pb2.AcceptPendingContractReply.SerializeToString,
            ),
            'RejectPendingContract': grpc.unary_unary_rpc_method_handler(
                    servicer.RejectPendingContract,
                    request_deserializer=rcdp__pb2.RejectPendingContractRequest.FromString,
                    response_serializer=rcdp__pb2.RejectPendingContractReply.SerializeToString,
            ),
            'GenerateHostInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.GenerateHostInfo,
                    request_deserializer=rcdp__pb2.GenerateHostInfoRequest.FromString,
                    response_serializer=rcdp__pb2.GenerateHostInfoReply.SerializeToString,
            ),
            'ChangeHostStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.ChangeHostStatus,
                    request_deserializer=rcdp__pb2.ChangeHostStatusRequest.FromString,
                    response_serializer=rcdp__pb2.ChangeHostStatusReply.SerializeToString,
            ),
            'TryAuthAtParticipant': grpc.unary_unary_rpc_method_handler(
                    servicer.TryAuthAtParticipant,
                    request_deserializer=rcdp__pb2.TryAuthAtParticipantRequest.FromString,
                    response_serializer=rcdp__pb2.TryAuthAtPartipantReply.SerializeToString,
            ),
            'ChangeUpdatesFromHostBehavior': grpc.unary_unary_rpc_method_handler(
                    servicer.ChangeUpdatesFromHostBehavior,
                    request_deserializer=rcdp__pb2.ChangeUpdatesFromHostBehaviorRequest.FromString,
                    response_serializer=rcdp__pb2.ChangesUpdatesFromHostBehaviorReply.SerializeToString,
            ),
            'ChangeDeletesFromHostBehavior': grpc.unary_unary_rpc_method_handler(
                    servicer.ChangeDeletesFromHostBehavior,
                    request_deserializer=rcdp__pb2.ChangeDeletesFromHostBehaviorRequest.FromString,
                    response_serializer=rcdp__pb2.ChangeDeletesFromHostBehaviorReply.SerializeToString,
            ),
            'ChangeUpdatesToHostBehavior': grpc.unary_unary_rpc_method_handler(
                    servicer.ChangeUpdatesToHostBehavior,
                    request_deserializer=rcdp__pb2.ChangeUpdatesToHostBehaviorRequest.FromString,
                    response_serializer=rcdp__pb2.ChangeUpdatesToHostBehaviorReply.SerializeToString,
            ),
            'ChangeDeletesToHostBehavior': grpc.unary_unary_rpc_method_handler(
                    servicer.ChangeDeletesToHostBehavior,
                    request_deserializer=rcdp__pb2.ChangeDeletesToHostBehaviorRequest.FromString,
                    response_serializer=rcdp__pb2.ChangeDeletesToHostBehaviorReply.SerializeToString,
            ),
            'GetDataHashAtHost': grpc.unary_unary_rpc_method_handler(
                    servicer.GetDataHashAtHost,
                    request_deserializer=rcdp__pb2.GetDataHashRequest.FromString,
                    response_serializer=rcdp__pb2.GetDataHashReply.SerializeToString,
            ),
            'GetDataHashAtParticipant': grpc.unary_unary_rpc_method_handler(
                    servicer.GetDataHashAtParticipant,
                    request_deserializer=rcdp__pb2.GetDataHashRequest.FromString,
                    response_serializer=rcdp__pb2.GetDataHashReply.SerializeToString,
            ),
            'ReadRowIdAtParticipant': grpc.unary_unary_rpc_method_handler(
                    servicer.ReadRowIdAtParticipant,
                    request_deserializer=rcdp__pb2.GetReadRowIdsRequest.FromString,
                    response_serializer=rcdp__pb2.GetReadRowIdsReply.SerializeToString,
            ),
            'GetDataLogTableStatusAtParticipant': grpc.unary_unary_rpc_method_handler(
                    servicer.GetDataLogTableStatusAtParticipant,
                    request_deserializer=rcdp__pb2.GetDataLogTableStatusRequest.FromString,
                    response_serializer=rcdp__pb2.GetDataLogTableStatusReply.SerializeToString,
            ),
            'SetDataLogTableStatusAtParticipant': grpc.unary_unary_rpc_method_handler(
                    servicer.SetDataLogTableStatusAtParticipant,
                    request_deserializer=rcdp__pb2.SetDataLogTableStatusRequest.FromString,
                    response_serializer=rcdp__pb2.SetDataLogTableStatusReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'rcdp.SQLClient', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class SQLClient(object):
    """a service for passing cooperative SQL statements to a rcd instance
    """

    @staticmethod
    def IsOnline(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/rcdp.SQLClient/IsOnline',
            rcdp__pb2.TestRequest.SerializeToString,
            rcdp__pb2.TestReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CreateUserDatabase(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/rcdp.SQLClient/CreateUserDatabase',
            rcdp__pb2.CreateUserDatabaseRequest.SerializeToString,
            rcdp__pb2.CreateUserDatabaseReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def EnableCoooperativeFeatures(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/rcdp.SQLClient/EnableCoooperativeFeatures',
            rcdp__pb2.EnableCoooperativeFeaturesRequest.SerializeToString,
            rcdp__pb2.EnableCoooperativeFeaturesReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ExecuteReadAtHost(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/rcdp.SQLClient/ExecuteReadAtHost',
            rcdp__pb2.ExecuteReadRequest.SerializeToString,
            rcdp__pb2.ExecuteReadReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ExecuteWriteAtHost(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/rcdp.SQLClient/ExecuteWriteAtHost',
            rcdp__pb2.ExecuteWriteRequest.SerializeToString,
            rcdp__pb2.ExecuteWriteReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ExecuteCooperativeWriteAtHost(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/rcdp.SQLClient/ExecuteCooperativeWriteAtHost',
            rcdp__pb2.ExecuteCooperativeWriteRequest.SerializeToString,
            rcdp__pb2.ExecuteCooperativeWriteReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ExecuteReadAtParticipant(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/rcdp.SQLClient/ExecuteReadAtParticipant',
            rcdp__pb2.ExecuteReadRequest.SerializeToString,
            rcdp__pb2.ExecuteReadReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ExecuteWriteAtParticipant(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/rcdp.SQLClient/ExecuteWriteAtParticipant',
            rcdp__pb2.ExecuteWriteRequest.SerializeToString,
            rcdp__pb2.ExecuteWriteReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def HasTable(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/rcdp.SQLClient/HasTable',
            rcdp__pb2.HasTableRequest.SerializeToString,
            rcdp__pb2.HasTableReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SetLogicalStoragePolicy(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/rcdp.SQLClient/SetLogicalStoragePolicy',
            rcdp__pb2.SetLogicalStoragePolicyRequest.SerializeToString,
            rcdp__pb2.SetLogicalStoragePolicyReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetLogicalStoragePolicy(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/rcdp.SQLClient/GetLogicalStoragePolicy',
            rcdp__pb2.GetLogicalStoragePolicyRequest.SerializeToString,
            rcdp__pb2.GetLogicalStoragePolicyReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GenerateContract(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/rcdp.SQLClient/GenerateContract',
            rcdp__pb2.GenerateContractRequest.SerializeToString,
            rcdp__pb2.GenerateContractReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def AddParticipant(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/rcdp.SQLClient/AddParticipant',
            rcdp__pb2.AddParticipantRequest.SerializeToString,
            rcdp__pb2.AddParticipantReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SendParticipantContract(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/rcdp.SQLClient/SendParticipantContract',
            rcdp__pb2.SendParticipantContractRequest.SerializeToString,
            rcdp__pb2.SendParticipantContractReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ReviewPendingContracts(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/rcdp.SQLClient/ReviewPendingContracts',
            rcdp__pb2.ViewPendingContractsRequest.SerializeToString,
            rcdp__pb2.ViewPendingContractsReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def AcceptPendingContract(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/rcdp.SQLClient/AcceptPendingContract',
            rcdp__pb2.AcceptPendingContractRequest.SerializeToString,
            rcdp__pb2.AcceptPendingContractReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def RejectPendingContract(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/rcdp.SQLClient/RejectPendingContract',
            rcdp__pb2.RejectPendingContractRequest.SerializeToString,
            rcdp__pb2.RejectPendingContractReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GenerateHostInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/rcdp.SQLClient/GenerateHostInfo',
            rcdp__pb2.GenerateHostInfoRequest.SerializeToString,
            rcdp__pb2.GenerateHostInfoReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ChangeHostStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/rcdp.SQLClient/ChangeHostStatus',
            rcdp__pb2.ChangeHostStatusRequest.SerializeToString,
            rcdp__pb2.ChangeHostStatusReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def TryAuthAtParticipant(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/rcdp.SQLClient/TryAuthAtParticipant',
            rcdp__pb2.TryAuthAtParticipantRequest.SerializeToString,
            rcdp__pb2.TryAuthAtPartipantReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ChangeUpdatesFromHostBehavior(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/rcdp.SQLClient/ChangeUpdatesFromHostBehavior',
            rcdp__pb2.ChangeUpdatesFromHostBehaviorRequest.SerializeToString,
            rcdp__pb2.ChangesUpdatesFromHostBehaviorReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ChangeDeletesFromHostBehavior(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/rcdp.SQLClient/ChangeDeletesFromHostBehavior',
            rcdp__pb2.ChangeDeletesFromHostBehaviorRequest.SerializeToString,
            rcdp__pb2.ChangeDeletesFromHostBehaviorReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ChangeUpdatesToHostBehavior(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/rcdp.SQLClient/ChangeUpdatesToHostBehavior',
            rcdp__pb2.ChangeUpdatesToHostBehaviorRequest.SerializeToString,
            rcdp__pb2.ChangeUpdatesToHostBehaviorReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ChangeDeletesToHostBehavior(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/rcdp.SQLClient/ChangeDeletesToHostBehavior',
            rcdp__pb2.ChangeDeletesToHostBehaviorRequest.SerializeToString,
            rcdp__pb2.ChangeDeletesToHostBehaviorReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetDataHashAtHost(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/rcdp.SQLClient/GetDataHashAtHost',
            rcdp__pb2.GetDataHashRequest.SerializeToString,
            rcdp__pb2.GetDataHashReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetDataHashAtParticipant(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/rcdp.SQLClient/GetDataHashAtParticipant',
            rcdp__pb2.GetDataHashRequest.SerializeToString,
            rcdp__pb2.GetDataHashReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ReadRowIdAtParticipant(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/rcdp.SQLClient/ReadRowIdAtParticipant',
            rcdp__pb2.GetReadRowIdsRequest.SerializeToString,
            rcdp__pb2.GetReadRowIdsReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetDataLogTableStatusAtParticipant(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/rcdp.SQLClient/GetDataLogTableStatusAtParticipant',
            rcdp__pb2.GetDataLogTableStatusRequest.SerializeToString,
            rcdp__pb2.GetDataLogTableStatusReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SetDataLogTableStatusAtParticipant(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/rcdp.SQLClient/SetDataLogTableStatusAtParticipant',
            rcdp__pb2.SetDataLogTableStatusRequest.SerializeToString,
            rcdp__pb2.SetDataLogTableStatusReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)


class DataServiceStub(object):
    """a service for communication between different rcd stores
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.IsOnline = channel.unary_unary(
                '/rcdp.DataService/IsOnline',
                request_serializer=rcdp__pb2.TestRequest.SerializeToString,
                response_deserializer=rcdp__pb2.TestReply.FromString,
                )
        self.CreatePartialDatabase = channel.unary_unary(
                '/rcdp.DataService/CreatePartialDatabase',
                request_serializer=rcdp__pb2.CreateDatabaseRequest.SerializeToString,
                response_deserializer=rcdp__pb2.CreateDatabaseResult.FromString,
                )
        self.CreateTableInDatabase = channel.unary_unary(
                '/rcdp.DataService/CreateTableInDatabase',
                request_serializer=rcdp__pb2.CreateTableRequest.SerializeToString,
                response_deserializer=rcdp__pb2.CreateTableResult.FromString,
                )
        self.InsertCommandIntoTable = channel.unary_unary(
                '/rcdp.DataService/InsertCommandIntoTable',
                request_serializer=rcdp__pb2.InsertDataRequest.SerializeToString,
                response_deserializer=rcdp__pb2.InsertDataResult.FromString,
                )
        self.UpdateCommandIntoTable = channel.unary_unary(
                '/rcdp.DataService/UpdateCommandIntoTable',
                request_serializer=rcdp__pb2.UpdateDataRequest.SerializeToString,
                response_deserializer=rcdp__pb2.UpdateDataResult.FromString,
                )
        self.DeleteCommandIntoTable = channel.unary_unary(
                '/rcdp.DataService/DeleteCommandIntoTable',
                request_serializer=rcdp__pb2.DeleteDataRequest.SerializeToString,
                response_deserializer=rcdp__pb2.DeleteDataResult.FromString,
                )
        self.GetRowFromPartialDatabase = channel.unary_unary(
                '/rcdp.DataService/GetRowFromPartialDatabase',
                request_serializer=rcdp__pb2.GetRowFromPartialDatabaseRequest.SerializeToString,
                response_deserializer=rcdp__pb2.GetRowFromPartialDatabaseResult.FromString,
                )
        self.SaveContract = channel.unary_unary(
                '/rcdp.DataService/SaveContract',
                request_serializer=rcdp__pb2.SaveContractRequest.SerializeToString,
                response_deserializer=rcdp__pb2.SaveContractResult.FromString,
                )
        self.AcceptContract = channel.unary_unary(
                '/rcdp.DataService/AcceptContract',
                request_serializer=rcdp__pb2.ParticipantAcceptsContractRequest.SerializeToString,
                response_deserializer=rcdp__pb2.ParticipantAcceptsContractResult.FromString,
                )
        self.UpdateRowDataHashForHost = channel.unary_unary(
                '/rcdp.DataService/UpdateRowDataHashForHost',
                request_serializer=rcdp__pb2.UpdateRowDataHashForHostRequest.SerializeToString,
                response_deserializer=rcdp__pb2.UpdateRowDataHashForHostResponse.FromString,
                )
        self.NotifyHostOfRemovedRow = channel.unary_unary(
                '/rcdp.DataService/NotifyHostOfRemovedRow',
                request_serializer=rcdp__pb2.NotifyHostOfRemovedRowRequest.SerializeToString,
                response_deserializer=rcdp__pb2.NotifyHostOfRemovedRowResponse.FromString,
                )
        self.TryAuth = channel.unary_unary(
                '/rcdp.DataService/TryAuth',
                request_serializer=rcdp__pb2.TryAuthRequest.SerializeToString,
                response_deserializer=rcdp__pb2.TryAuthResult.FromString,
                )


class DataServiceServicer(object):
    """a service for communication between different rcd stores
    """

    def IsOnline(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreatePartialDatabase(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateTableInDatabase(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def InsertCommandIntoTable(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateCommandIntoTable(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteCommandIntoTable(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetRowFromPartialDatabase(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SaveContract(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AcceptContract(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateRowDataHashForHost(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def NotifyHostOfRemovedRow(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def TryAuth(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DataServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'IsOnline': grpc.unary_unary_rpc_method_handler(
                    servicer.IsOnline,
                    request_deserializer=rcdp__pb2.TestRequest.FromString,
                    response_serializer=rcdp__pb2.TestReply.SerializeToString,
            ),
            'CreatePartialDatabase': grpc.unary_unary_rpc_method_handler(
                    servicer.CreatePartialDatabase,
                    request_deserializer=rcdp__pb2.CreateDatabaseRequest.FromString,
                    response_serializer=rcdp__pb2.CreateDatabaseResult.SerializeToString,
            ),
            'CreateTableInDatabase': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateTableInDatabase,
                    request_deserializer=rcdp__pb2.CreateTableRequest.FromString,
                    response_serializer=rcdp__pb2.CreateTableResult.SerializeToString,
            ),
            'InsertCommandIntoTable': grpc.unary_unary_rpc_method_handler(
                    servicer.InsertCommandIntoTable,
                    request_deserializer=rcdp__pb2.InsertDataRequest.FromString,
                    response_serializer=rcdp__pb2.InsertDataResult.SerializeToString,
            ),
            'UpdateCommandIntoTable': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateCommandIntoTable,
                    request_deserializer=rcdp__pb2.UpdateDataRequest.FromString,
                    response_serializer=rcdp__pb2.UpdateDataResult.SerializeToString,
            ),
            'DeleteCommandIntoTable': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteCommandIntoTable,
                    request_deserializer=rcdp__pb2.DeleteDataRequest.FromString,
                    response_serializer=rcdp__pb2.DeleteDataResult.SerializeToString,
            ),
            'GetRowFromPartialDatabase': grpc.unary_unary_rpc_method_handler(
                    servicer.GetRowFromPartialDatabase,
                    request_deserializer=rcdp__pb2.GetRowFromPartialDatabaseRequest.FromString,
                    response_serializer=rcdp__pb2.GetRowFromPartialDatabaseResult.SerializeToString,
            ),
            'SaveContract': grpc.unary_unary_rpc_method_handler(
                    servicer.SaveContract,
                    request_deserializer=rcdp__pb2.SaveContractRequest.FromString,
                    response_serializer=rcdp__pb2.SaveContractResult.SerializeToString,
            ),
            'AcceptContract': grpc.unary_unary_rpc_method_handler(
                    servicer.AcceptContract,
                    request_deserializer=rcdp__pb2.ParticipantAcceptsContractRequest.FromString,
                    response_serializer=rcdp__pb2.ParticipantAcceptsContractResult.SerializeToString,
            ),
            'UpdateRowDataHashForHost': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateRowDataHashForHost,
                    request_deserializer=rcdp__pb2.UpdateRowDataHashForHostRequest.FromString,
                    response_serializer=rcdp__pb2.UpdateRowDataHashForHostResponse.SerializeToString,
            ),
            'NotifyHostOfRemovedRow': grpc.unary_unary_rpc_method_handler(
                    servicer.NotifyHostOfRemovedRow,
                    request_deserializer=rcdp__pb2.NotifyHostOfRemovedRowRequest.FromString,
                    response_serializer=rcdp__pb2.NotifyHostOfRemovedRowResponse.SerializeToString,
            ),
            'TryAuth': grpc.unary_unary_rpc_method_handler(
                    servicer.TryAuth,
                    request_deserializer=rcdp__pb2.TryAuthRequest.FromString,
                    response_serializer=rcdp__pb2.TryAuthResult.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'rcdp.DataService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class DataService(object):
    """a service for communication between different rcd stores
    """

    @staticmethod
    def IsOnline(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/rcdp.DataService/IsOnline',
            rcdp__pb2.TestRequest.SerializeToString,
            rcdp__pb2.TestReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CreatePartialDatabase(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/rcdp.DataService/CreatePartialDatabase',
            rcdp__pb2.CreateDatabaseRequest.SerializeToString,
            rcdp__pb2.CreateDatabaseResult.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CreateTableInDatabase(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/rcdp.DataService/CreateTableInDatabase',
            rcdp__pb2.CreateTableRequest.SerializeToString,
            rcdp__pb2.CreateTableResult.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def InsertCommandIntoTable(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/rcdp.DataService/InsertCommandIntoTable',
            rcdp__pb2.InsertDataRequest.SerializeToString,
            rcdp__pb2.InsertDataResult.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def UpdateCommandIntoTable(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/rcdp.DataService/UpdateCommandIntoTable',
            rcdp__pb2.UpdateDataRequest.SerializeToString,
            rcdp__pb2.UpdateDataResult.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DeleteCommandIntoTable(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/rcdp.DataService/DeleteCommandIntoTable',
            rcdp__pb2.DeleteDataRequest.SerializeToString,
            rcdp__pb2.DeleteDataResult.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetRowFromPartialDatabase(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/rcdp.DataService/GetRowFromPartialDatabase',
            rcdp__pb2.GetRowFromPartialDatabaseRequest.SerializeToString,
            rcdp__pb2.GetRowFromPartialDatabaseResult.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SaveContract(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/rcdp.DataService/SaveContract',
            rcdp__pb2.SaveContractRequest.SerializeToString,
            rcdp__pb2.SaveContractResult.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def AcceptContract(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/rcdp.DataService/AcceptContract',
            rcdp__pb2.ParticipantAcceptsContractRequest.SerializeToString,
            rcdp__pb2.ParticipantAcceptsContractResult.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def UpdateRowDataHashForHost(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/rcdp.DataService/UpdateRowDataHashForHost',
            rcdp__pb2.UpdateRowDataHashForHostRequest.SerializeToString,
            rcdp__pb2.UpdateRowDataHashForHostResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def NotifyHostOfRemovedRow(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/rcdp.DataService/NotifyHostOfRemovedRow',
            rcdp__pb2.NotifyHostOfRemovedRowRequest.SerializeToString,
            rcdp__pb2.NotifyHostOfRemovedRowResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def TryAuth(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/rcdp.DataService/TryAuth',
            rcdp__pb2.TryAuthRequest.SerializeToString,
            rcdp__pb2.TryAuthResult.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
